### ISSUE TITLE
Udostepniony wynik - nie moje rozwiazanie

### ISSUE THREAD

**Issue by camonday** [Deykun/diffle-lang#25]
Po przejsciu do udostepniony wynik wyświetla się rozwiązanie ktore nie jest moje. Jak widaz na załączonym zrzucie mój wynik to 4 słowa, a "udostępniony" to dwa słowa.
![419695224_1795965870848589_9050370405414332129_n](https://github.com/Deykun/diffle-lang/assets/35116333/85585a26-574a-4b2c-b290-71f5df6ea196)
![419175800_894962212177729_7766936613861718613_n](https://github.com/Deykun/diffle-lang/assets/35116333/d38f5edd-28c5-4869-8f71-ea886463bfb0)

**Comment by Deykun** [comment]
@camonday hej, to wynik udostępniony Tobie, a nie Twój. :)

Wszedłeś z pierwszego URLa tutaj:
https://www.hejto.pl/wpis/15-01-2024-flag-pl-diffle-19-liter-w-2-slowach-large-green-circle-7-large-yellow

https://deykun.github.io/diffle-lang/?r=ESKy0ycldmL5QzNz0ieyBnLw4iMx4CMucjL0NXZnhSI

![obraz](https://github.com/Deykun/diffle-lang/assets/21176665/419fe86a-2a29-4519-abfb-dce01610def3)

Swój tekst i url dotaniesz klikając "Skopiuj wynik". :)

**Comment by camonday** [comment]
może lepiej "udostępniony Tobie"

**Comment by Deykun** [comment]
Nie chcę za długiego robić:

### Po aktualizacji
![obraz](https://github.com/Deykun/diffle-lang/assets/21176665/37758836-2d2a-43ef-b622-511f08633644)

https://deykun.github.io/diffle-lang/?r=ESKy0ycldmL5QzNz0ieyBnLw4iMx4CMucjL0NXZnhSI
